name: Build and push Redirect

on:
  push:
    branches:
      - devredirect

jobs:

  build-and-push:
    runs-on: ubuntu-latest
#    needs: build
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/redirect:latest -f docker/redirect/Dockerfile .
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/redirect:latest